<!doctype html>
<html>
    <head>
        <title>TravelBlog</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="<?php echo $this->webhost; ?>asset/css">
    </head>
    <body>
        <?php echo $this->render('partial/menu.phtml'); ?>

        <div class="container">
            <?php echo $this->render($this->template); ?>
        </div>

        <script src="<?php echo $this->webhost; ?>asset/js/c/<?php echo $this->request->get('controller'); ?>/a/<?php echo $this->request->get('action'); ?>"></script>
    </body>
</html>
