<!doctype html>
<html>
    <head>
        <title>TravelBlog</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="<?php echo $this->cdnhost; ?>asset/css/main.css?v=<?php echo $this->config['version']; ?>">
        <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
        <?php if ($this->includeMapGl): ?>
            <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.52.0/mapbox-gl.css' rel='stylesheet' />
        <?php endif; ?>
        <?php if ($this->og): ?>
            <?php foreach ($this->og as $key => $value): ?>
                <meta property="og:<?php echo $key; ?>" content="<?php echo $value; ?>" />
            <?php endforeach; ?>
        <?php endif; ?>
    </head>
    <body class="con-<?php echo $this->request->get('controller'); ?>">
        <?php echo $this->render('partial/menu.phtml'); ?>

        <?php if ($this->header): ?>
            <!-- Page Header -->
            <header class="masthead" <?php if (isset($this->header['image'])): ?> style="background-image: url('<?php echo $this->header['image']; ?>')"<?php endif; ?>>
                <div class="overlay"></div>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8 col-md-10 mx-auto">
                            <div class="page-heading">
                                <h1><?php echo $this->t($this->header['title']); ?></h1>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
        <?php endif; ?>

        <div class="container-fluid">
            <?php if ($this->mainTitle): ?>
                <h2 class="bd-title"><php echo $this->mainTitle; ?></h2>
            <?php endif; ?>

            <?php echo $this->render($this->template); ?>
        </div>

        <?php echo $this->render('partial/footer.phtml'); ?>


        <script src="<?php echo $this->cdnhost; ?>asset/js/mootools-compat.js"></script>
        <script src="<?php echo $this->cdnhost; ?>asset/js/t/jquery"></script>
        <script src="<?php echo $this->cdnhost; ?>asset/js/c/<?php echo $this->request->get('controller'); ?>/a/<?php echo $this->request->get('action'); ?>?v=<?php echo $this->config['version']; ?>"></script>
        <?php if ($this->includeMapGl): ?>
            <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.52.0/mapbox-gl.js'></script>
        <?php endif; ?>
    </body>
</html>
