
<div class="row pie-stat">
    <div class="col-md-12 col-lg-6">
        <svg viewBox="0 0 320 320" class="pie">
            <?php $offset = 500; foreach (array_reverse($this->values, true) as $key => $value): ?>
                <circle class="value value-<?php echo $key+1; ?>" r="79" cx="160" cy="160"
                    style="stroke-dasharray: <?php echo $offset; ?> 500"
                />
            <?php $offset -= ($value['perc'] * 5); endforeach; ?>
        </svg>
    </div>
    <div class="col-md-12 col-lg-6">
        <?php foreach ($this->values as $key => $value): ?>
            <p class="entry entry-<?php echo $key + 1; ?>">
                <?php if (strpos($this->t($value['key']), 'fa') === 0): ?>
                    <i class="<?php echo $this->t($value['key']); ?>"></i>
                <?php else: ?>
                    <?php echo $this->t($value['key']); ?>:
                <?php endif; ?>
                <span class="value">
                    <?php echo $value['value']; ?>
                </span>
            </p>
        <?php endforeach; ?>
    </div>
</div>
