<div class="post-preview">

  <a href="<?php echo $this->webhost . 'post/id/' . $this->id; ?>">
    <h2 class="post-title"><?php echo $this->title; ?></h2>
    <h3 class="post-subtitle"><?php echo $this->subtitle; ?></h3>
    <?php if (count($this->files) > 1): ?>
        <?php echo $this->render('partial/post/imagebox.phtml'); ?>
    <?php elseif (isset($this->files[0])): ?>
        <img class="post-picture" src="<?php echo $this->webhost; ?>asset/post/id/<?php echo $this->id; ?>/f/<?php echo $this->files[0]; ?>">
    <?php endif; ?>
  </a>
  <p class="post-meta"><?php echo $this->t('posted.by'); ?>
    <a href="#"><?php echo $this->author; ?></a>
    <?php echo $this->t('on'); ?> <?php echo $this->date($this->posted); ?></p>
</div>
<?php //var_dump($this); ?>
