<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="<?php echo $this->webhost; ?>">Zum Blog</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-main">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar-main">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="<?php echo $this->webhost; ?>admin/index">Posts</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<?php echo $this->webhost; ?>admin/meta-list">Meta</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<?php echo $this->webhost; ?>admin/stat-list">Stats</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<?php echo $this->webhost; ?>admin/translation-list">Übersetzungen</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<?php echo $this->webhost; ?>admin/logout">Logout</a>
            </li>
        </ul>
    </div>

    <div class="collapse navbar-collapse justify-content-end" id="navbar-profile">
        <ul class="navbar-nav ">

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <?php echo $this->user['login']; ?>
                </a>

                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="<?php echo $this->webhost; ?>admin/logout">Logout</a>
                </div>
            </li>
        </ul>
    </div>
</nav>
