
    <!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="<?php echo $this->webhost; ?>">
            <img src="<?php echo $this->cdnhost; ?>asset/img/logo-white.png">
        </a>
        <button class="navbar-toggler pull-right navbar-toggler-left" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo $this->webhost; ?>map/route"><?php echo $this->t('route'); ?></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo $this->webhost; ?>page/aboutus"><?php echo $this->t('about.us'); ?></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="tagDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <?php echo $this->t('tags'); ?>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="tagDropdown">
                        <?php foreach ($this->postTags as $tag): ?>
                            <a class="dropdown-item" href="<?php echo $this->webhost . 'post/by/tag/' . $tag['value']; ?>">
                                <?php echo $tag['value']; ?>
                            </a>
                        <?php endforeach; ?>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="countryDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <?php echo $this->t('countries'); ?>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="countryDropdown">
                        <?php foreach ($this->postCountries as $country): ?>
                            <a class="dropdown-item" href="<?php echo $this->webhost . 'post/by/country/' . $country['country_code']; ?>">
                                <?php echo $this->i18n('country', $country['country_code']); ?>
                            </a>
                        <?php endforeach; ?>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="languageDropdown" data-toggle="dropdown">
                        <?php echo $this->t('language'); ?>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <?php foreach ($this->locales as $locale): ?>
                            <a class="dropdown-item <?php if ($locale == $this->currentLocale): ?>font-weight-bold<?php endif; ?>" href="<?php echo $this->webhost . $this->request->get('path'); ?>?language=<?php echo $locale; ?>">
                                <?php echo $this->t(substr($locale, 0, 2)); ?>
                            </a>
                        <?php endforeach; ?>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
