
    <!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="<?php echo $this->webhost; ?>">
            <img src="<?php echo $this->webhost; ?>asset/img/logo-white.png">
        </a>
        <button class="navbar-toggler pull-right navbar-toggler-left" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">

                <li class="nav-item">
                    <a class="nav-link" href="<?php echo $this->webhost; ?>page/aboutus"><?php echo $this->t('about.us'); ?></a>
                </li>
            </ul>
        </div>
    </div>
</nav>
