
<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post">
            <?php echo $this->t('stat.text'); ?>
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <ul class="list-group">
                        <?php foreach ($this->stats as $stat): ?>
                            <li class="list-group-item d-flex justify-content-between align-items-center<?php if ($stat['head']): ?> list-group-item-dark<?php endif; ?>">
                                <?php echo $this->t($stat['key']); ?>
                                <?php if (!$stat['head']): ?>
                                    <span class="badge badge-danger badge-pill"><?php echo $stat['value']; ?></span>
                                <?php endif; ?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
