<div class="row">
    <div class="col-md ">
        <div class="card">
            <div class="card-header">
                <?php echo $this->t('meta.overview'); ?>
                <a class="btn btn-sm btn-primary float-right" href="<?php echo $this->webhost; ?>admin/meta">
                    <?php echo $this->t('add.meta'); ?>
                </a>
            </div>
            <div class="card-body">
                <?php echo $this->table; ?>
            </div>
        </div>
    </div>
</div>
