
<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <div class="page-heading">
        </div>
        <div class="post">
            <div class="geo-map" id="map" data-boundaries='<?php echo json_encode($this->boundaries); ?>'></div>
            <script>
                var markers = <?php echo json_encode($this->markers); ?>;
            </script>
        </div>
    </div>
</div>
