<div class="file-preview">
    <?php foreach ($this->value as $file): ?>
        <div class="image-wrapper float-left p-4" data-post-id="<?php echo $file['post_id']; ?>" data-file="<?php echo $file['filename']; ?>">
            <button class="btn btn-danger rounded-circle btn-sm delete-file">
                <i class="fas fa-trash"></i>
            </button>
            <img class="img-responsive" src="<?php echo $this->webhost; ?>asset/post/s/xs/id/<?php echo $file['post_id']; ?>/f/<?php echo $file['filename']; ?>">
            <div class="input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text">
                        <?php echo $this->t('file.name'); ?>
                    </div>
                </div>
                <input style="width: 30px;" type="text" readonly class="form-control" value=<?php echo $file['name']; ?>>
            </div>
            <div class="input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text">
                        <?php echo $this->t('post.media.order'); ?>
                    </div>
                </div>
                <input style="width: 30px;" type="number" class="form-control sort-order meta-data" value=<?php echo $file['sort']; ?>>
            </div>
            <div class="input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text">
                        <?php echo $this->t('post.media.subtitle'); ?>
                    </div>
                </div>
                <input style="width: 30px;" type="text" class="form-control media-subtitle meta-data" value=<?php echo $file['subtitle']; ?>>
            </div>
        </div>
    <?php endforeach; ?>
</div>
