<div class="file-preview">
    <?php foreach ($this->value as $file): ?>
        <div class="image-wrapper float-left p-4" data-post-id="<?php echo $file['post_id']; ?>" data-file="<?php echo $file['filename']; ?>" data-sort="<?php echo $file['sort']; ?>">
            <div class="image-actions">
                <button class="btn btn-primary rounded-circle btn-sm sort sort-up">
                    <i class="fas fa-arrow-up"></i>
                </button>
                <button class="btn btn-primary rounded-circle btn-sm sort sort-down">
                    <i class="fas fa-arrow-down"></i>
                </button>
                <button class="btn btn-danger rounded-circle btn-sm delete-file">
                    <i class="fas fa-trash"></i>
                </button>
            </div>
            <?php if (strpos($file['type'], 'video') !== 0): ?>
                <img class="img-responsive" src="<?php echo $this->webhost; ?>asset/post/s/xs/id/<?php echo $file['post_id']; ?>/f/<?php echo $file['filename']; ?>">
            <?php else: ?>
                <video controls preload="auto" src="<?php echo $this->webhost; ?>asset/post/id/<?php echo $file['post_id']; ?>/f/<?php echo $file['filename']; ?>" width="100%"></video>
            <?php endif; ?>
            <input type="hidden" readonly class="form-control" value=<?php echo $file['name']; ?>>
            <input type="hidden" value="<?php echo $file['sort']; ?>">
            <div class="input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text">
                        <?php echo $this->t('post.media.subtitle'); ?>
                    </div>
                </div>
                <input style="width: 30px;" type="text" class="form-control media-subtitle meta-data" value="<?php echo $file['subtitle']; ?>">
            </div>
        </div>
    <?php endforeach; ?>
</div>
