
<div class="pagination">
    <?php if ($this->page > 1): ?>
        <a href="#" data-page="1">&laquo;</a>
        <a href="#" data-page="<?php echo $this->page - 1; ?>">&lsaquo;</a>
    <?php endif; ?>
    <?php if ($this->total_pages > $this->max_pages): ?>
        <?php if ($this->pages_from > 1): ?><span class="hint">...</span><?php endif; ?>
        <?php for ($i = 0; $i < $this->max_pages; $i++): ?>
            <?php if ($i !== 0): ?> | <?php endif; ?>
            <a href="#" class="<?php if ($this->pages_from + $i == $this->page): ?>active<?php endif; ?>" data-page="<?php echo $this->pages_from + $i; ?>"><?php echo $this->pages_from + $i; ?></a>
        <?php endfor; ?>
        <?php if ($this->pages_from < $this->total_pages - $this->max_pages): ?><span class="hint">...</span></php endif; ?><?php endif; ?>
    <?php elseif ($this->total_pages > 1): ?>
        <?php for ($i = 1; $i <= $this->total_pages; $i++): ?>
            <a href="#" class="<?php if (($i) == $this->page): ?>active<?php endif; ?>" data-page="<?php echo $i; ?>"><?php echo $i; ?></a>
        <?php endfor; ?>
    <?php endif; ?>
    <?php if ($this->page < $this->total_pages): ?>
        <a href="#" data-page="<?php echo $this->page + 1; ?>">&rsaquo;</a>
        <a href="#" data-page="<?php echo $this->total_pages; ?>">&raquo;</a>
    <?php endif; ?>
</div>
