
<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <?php if (isset($this->config['instagram']) && $this->config['instagram']): ?>
                        <li class="list-inline-item">
                            <a href="https://instagram.com/<?php echo $this->config['instagram']; ?>" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-instagram fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    <?php endif; ?>
                    <li class="list-inline-item">
                        <a href="https://github.com/hmusche/travelblog" target="_blank">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>

                    <p class="text-muted copyright">
                        <a href="<?php echo $this->webhost; ?>page/impressum"><?php echo $this->t('impressum'); ?></a> |
                        <a href="<?php echo $this->webhost; ?>page/dpr"><?php echo $this->t('data.protection'); ?></a>
                    </p>
                <p class="copyright text-muted">Copyright &copy; no-fly-zone.de <?php echo date('Y'); ?> | <a href="<?php echo $this->webhost; ?>admin">Admin</a></p>
            </div>
        </div>
    </div>
</footer>

<?php if (!$this->acceptCookie): ?>
    <div class="cookie-notice">
        <p><?php echo sprintf($this->t('cookie.notice'), $this->webhost . 'page/dpr', $this->t('data.protection')); ?></p>
        <button class="btn btn-primary cookie-accept"><?php echo $this->t('cookie.accept') ; ?></button>
    </div>
<?php endif; ?>
