<div class="card solsken-form">
    <form action="<?php echo $this->webhost . $this->path; ?>" method="post" enctype="multipart/form-data" id="<?php echo $this->formId; ?>">
        <div class="card-header clearfix">
            <div class="label float-left">
                <?php echo $this->t($this->label); ?>
            </div>

            <div class="tools float-right">
                <?php echo $this->submit; ?>
                <?php if (isset($this->options['actions'])): ?>
                    <?php foreach ($this->options['actions'] as $action): ?>
                        <?php echo $this->partial('partial/form/action.phtml', $action); ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
        </div>
        <div class="card-body">
            <?php if ($this->errors): ?>
                <?php echo $this->t('check.errors'); ?>
            <?php endif; ?>
            <?php if ($this->groups): ?>
                <div class="row">
                    <?php foreach ($this->groups as $group): ?>
                        <div class="group-<?php echo $group['name']; ?> <?php echo $group['class'] ?: 'col-xs-12'; ?>">
                            <?php foreach ($group['elements'] as $element): ?>
                                <?php echo $element; ?>
                            <?php endforeach; ?>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php else: ?>
                <div class="row">
                    <div class="col">
                        <?php foreach ($this->elements as $key => $element): ?>
                            <?php echo $element; ?>
                        <?php endforeach; ?>
                    </div>
                </div>
            <?php endif; ?>

            <div class="row">
                <div class="col">
                    <input type="hidden" value="<?php echo $this->formId; ?>" name="form_id">
                    <?php echo $this->submit; ?>
                </div>
            </div>
        </div>
    </form>
</div>
