
    <div class="solsken-gallery">
        <div class="gallery-wrapper">
            <?php foreach ($this->files as $file): ?>
                <div class="gallery-image-wrapper" data-src="<?php echo $this->cdnhost; ?><?php echo $file; ?>">
                </div>
            <?php endforeach; ?>
        </div>
        <div class="gallery-controls">
            <div class="gallery-left"></div>
            <div class="gallery-right"></div>
            <div class="gallery-fullscreen-button"><i class="fas fa-arrows-alt"></i></div>
        </div>
    </div>
