<?php $config = $this->table->getTableConfig(); ?>
<div class="solsken-table" data-identifier="<?php echo $this->table->getIdentifier(); ?>">
    <table class="table table-bordered table-responsive-sm<?php if ($this->table->hasRowAction()): ?> table-hover<?php endif; ?>">
        <thead>
            <tr>
                <?php if ($this->table->hasActions()): ?>
                    <th></th>
                <?php endif ?>
                <?php foreach ($this->table->getColumns() as $column): ?>
                    <?php echo $this->partial('partial/table/column.phtml', ['col' => $column, 'config' => $config]); ?>
                <?php endforeach; ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->table->getRows() as $key => $row): ?>
                <?php echo $this->partial('partial/table/row.phtml', ['row' => $row]); ?>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php if ($config): ?>
        <?php echo $this->partial('partial/table/pagination.phtml', $config['pagination']); ?>
    <?php endif; ?>
</div>
