<div class="form-group form-check">
    <input type="hidden" name="<?php echo $this->element->getName(); ?>" value="0">
    <input type="checkbox" <?php if ($this->element->getValue()): ?>checked="checked" <?php endif; ?><?php echo $this->element->getAttributeString(); ?> id="element-<?php echo $this->element->getName(); ?>" name="<?php echo $this->element->getName(); ?>" value="1">
    <label for="element-<?php echo $this->element->getName(); ?>"><?php echo $this->t($this->element->getLabel()); ?></label>
    <?php if ($this->element->hasErrors()): ?>
        <small class="form-text text-alert"><?php echo implode('<br>', $this->element->getErrors()); ?></small>
    <?php endif; ?>
</div>
