
<div class="form-group">
    <label for="element-<?php echo $this->element->getName(); ?>"><?php echo $this->element->getLabel(); ?></label>
    <select class="form-control" <?php echo $this->element->getAttributeString(); ?> id="element-<?php echo $this->element->getName(); ?>" name="<?php echo $this->element->getName(); ?>">
        <?php foreach ($this->element->getSelect() as $key => $value): ?>
            <option value="<?php echo $key; ?>"<?php if ($this->element->getValue() == $key):?> selected="selected"<?php endif; ?>><?php echo $value; ?></option>
        <?php endforeach; ?>
    </select>
    <?php if ($this->element->hasErrors()): ?>
        <small class="form-text text-alert"><?php echo implode('<br>', $this->element->getErrors()); ?></small>
    <?php endif; ?>
</div>
