
<div class="form-group">
    <label for="element-<?php echo $this->element->getName(); ?>"><?php echo $this->t($this->element->getLabel()); ?></label>
    <textarea <?php echo $this->element->getAttributeString(['class' => 'form-control']); ?> id="element-<?php echo $this->element->getName(); ?>" name="<?php echo $this->element->getName(); ?>"><?php echo $this->element->getValue(); ?></textarea>
    <?php if ($this->element->hasErrors()): ?>
        <small class="form-text text-alert"><?php echo implode('<br>', $this->element->getErrors()); ?></small>
    <?php endif; ?>
</div>
